### ISSUE TITLE
Re-implement the timeline with D3js instead of using vuetify timeline component

### ISSUE THREAD

**Issue by YangQi007** [iobio/patient_portal#1]
Need to address several scenarios:

1, Maybe only one or none event happened in whole year
2, Show the whole time range together on UI view instead of showing long time range by scroll bar
3, Consider how to show the event time if the timestamp itself is also PHI
4, How to solve 'events happened same time', maybe stack them on view?

**Comment by AlistairNWard** [comment]
These all make sense. It might make sense to make some very simple mockups that we can discuss as a group. If we have a timeline that spans multiple years, we may find it's impractical to fit the whole timeline in a view with no scroll. Also, if someone has a small screen, this may also present a problem. So I wouldn't throw out any possible ideas until we think through the possible data.
- We may be able to keep the timeline without a scroll by collapsing information
- We may prefer using a scroll, but have the present time always centered, e.g. if there is an event planned in a year from now and we have 2 years of history, the default timeline view might only have 6 months of events centered on the present so you can already scroll in both directions?

I guess the point is that we probably shouldn't throw out any solution immediately, but think through possible solutions. Happy to set up meetings to discuss

**Comment by YangQi007** [comment]
Add the link of timeline mockup: https://www.figma.com/file/tTWdSomKssBUyPaaN6Ok4u/New-Timeline?type=design&node-id=0-1&mode=design&t=u5a1BbkI5CwVWTJA-0
